
guis:
# |=======================|
# |   /ah - main Page GUI |
# |=======================|
  main_page:
    title: "<dark_gray>Market - ur-server.de"
    sort_options:
      enabled:
        name_a_z: "<blue>Name A -> Z"
        name_z_a: "<blue>Name Z -> A"
        price_h_l: "<blue>Price High -> Low"
        price_l_h: "<blue>Price Low -> High"
        price_per_piece_h_l: "<blue>Price/piece High -> Low"
        price_per_piece_l_h: "<blue>Price/piece Low -> High"
      disabled:
        name_a_z: "<gray>Name A -> Z"
        name_z_a: "<gray>Name Z -> A"
        price_h_l: "<gray>Price High -> Low"
        price_l_h: "<gray>Price Low -> High"
        price_per_piece_h_l: "<gray>Price/piece High -> Low"
        price_per_piece_l_h: "<gray>Price/piece Low -> High"
    items:
      # Supported placeholder: {ITEM_NAME}, {PRICE}
      listing:
        name: "{ITEM_NAME}"
      lore_header:
        - "<gray>(<b><green>{PRICE}</green></b><yellow>$</yellow>)</gray>"
        - "<gray>LinksKlick zum Kaufen"
        - "<gray>RechtsKlick für Mehr Informationen"
      arrow_left:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      settings:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      my_listings:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      create_listing:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      sort:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
      search:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      arrow_right:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
  # |============================================|
  # |   /ah -> create Listing GUI - select item  |
  # |============================================|
  create_listing_1:
    title: "<dark_gray>Create Listing - Select Item"
    items:
      cancel:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This isA Placeholder"
          - "<gray>configure at AstrAH/config.yml"
  # |=====================================|
  # |   /ah -> create Listing GUI - price  |
  # |=====================================|
  create_listing_2:
    lines:
      1: "^^^^^^^^^^^^^^^"
      2: "Set Price"
      3: "_______________"
  # |================================================|
  # |   /ah -> create Listing GUI - preview listing  |
  # |================================================|
  create_listing_3:
    title: "<dark_gray>Create Listing - Confirm"
    items:
      confirm:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      cancel:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
  # |==========================|
  # |   /ah -> settings GUI    |
  # |==========================|
  settings:
    title: "<dark_gray>Settings"
    items:
      categories_toggle:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      history_toggle:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      default_filter:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      default_category:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
  # |=================================|
  # |   /ah -> player listings GUI    |
  # |=================================|
  my_listings:
    title: "<dark_gray>My listings"
    items:
      back:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      next_page:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      previous_page:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
  listing_info:
    title: "<dark_gray>Listing details"
    show_seller_head: false
    items:
      # seller_head and info support the following placeholders: {SELLER_NAME}, {BUYER_BALANCE}, {ITEM_PRICE}, {ITEM_NAME}, {ITEM_DISPLAY_NAME}, {ITEM_COUNT}, {PRICE_PER_PIECE}
      seller_head:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      info:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"
      back:
        material: BARRIER
        amount: 1
        display-name: "<gray>Placeholder"
        lore:
          - "<gray>This is a Placeholder"
          - "<gray>configure at AstrAH/config.yml"

categories:
  filter0:
    item:
      material: BARRIER
      amount: 1
      display-name: "<gray>Filter Deaktivieren</gray>"
      lore:
        - "<gray>klicken um Filter zu deaktivieren"
    rules:
      - "**"
  filter1:
      item:
        material: SANDSTONE
        amount: 1
        display-name: "<gray>Baumaterialien</gray>"
        lore:
          - "<gray>klicken um Filter zu aktivieren"
      rules:
        - "*STONE*"
        - "*PICKAXE*"
        - "*SHOVEL*"
        - "*AXE*"
  filter2:
    item:
      material: STONE
      amount: 1
      display-name: "<gold>Filter2</gold>"
      lore:
        - "<gray>Erste Zeile"
        - "<gray>Zweite Zeile"
    rules:
      - "*GOLD*"
      - "*IRON*"
      - "*DEEPSLATE*"
      - "*AXE*"
  filter3:
    item:
      material: BARRIER
      amount: 1
      display-name: "<gray>Filter Deaktivieren</gray>"
      lore:
        - "<gray>klicken um Filter zu deaktivieren"
    rules:
      - "*"
  filter4:
    item:
      material: SANDSTONE
      amount: 1
      display-name: "<gray>Baumaterialien2</gray>"
      lore:
        - "<gray>klicken um Filter zu aktivieren"
    rules:
      - "*STONE*"
      - "*PICKAXE*"
      - "*SHOVEL*"
      - "*AXE*"
  filter5:
    item:
      material: STONE
      amount: 1
      display-name: "<gold>Filter4</gold>"
      lore:
        - "<gray>Erste Zeile"
        - "<gray>Zweite Zeile"
    rules:
      - "*GOLD*"
      - "*IRON*"
      - "*DEEPSLATE*"
      - "*AXE*"

settings:
  # here you can decide how much players can customize their UI layout and what actions they are allowed to do.
  # if a preference is disabled it will allways be the default value.
  # Disabled actions will not appear as buttons on the inventory pages.
  # you can set the values to "permission", "true" or "false" to set default values for players.
  # To change these values for individual players visit the ingame admin UI. Changes made in the ingame UI will always Overwrite defaults.
  actions:
    manage_preferences:
      show_advanced_categories: true
      show_advanced_history: true
      reload_on_open: true
      default_filter: true
      default_sort: true
    categories: true
    settings: true
    my_listings: true
    refresh: true
    sort: true
    search: true
    history: true

  # The default settings for new players. if not disabled under xx.xx players will be able to change these settings at any time themself.
  defaults:
    # should players always see their default settings or get to the last screen they opened when entering the /ah command
    # if set to true when opening the auctionhouse a player will allways see the first page and their default filter/category when opening the menu
    # when set to false players will be brought back to their last viewed page when opening the menu to e.g. continue selling an item.
    reload_on_open: false
    # The setting "advanced categories" will change how the UI is structured.
    # If set to true by default players will find all configured categories scrollable in the left row of the page, with the bottom and top item beeing the configured scroll item .
    # if set to false players will see the configured categories Item which allows them to cycle through categories by lef/right clicking.
    show_advanced_categories: true
    # The setting "advanced_history" will change ho the UI is structured.
    # If set to true by default players will find a scrollable list of their last purchased items on the right side of the main page.
    # By left clicking they can set their Filters to match the item and auto sort by cheapest price.
    # if set to false players will see the configured history Item on the bottom of the page which allows the to cycle through the options by left/right clicking.
    show_advanced_history: true


  economy:
    tax_percentage: 10
#    supported economy providers at the time are:
#      plugins: "astraeconomy", "vault", "coinsengine" ...
#      other: "auto", "file".
#    setting this to auto will use the first compatible plugin in the order they are written above.
#    if none work it will use a file to store balances and provide basic commands for players to use money.
#    keep in mind that the built in economy is not compatible with other plugins and is intended for small servers where the Auctionhouse is the only way players interact with money
    provider: "auto"
  storage:
#   Available Storage providers are: "file"
    provider: "file"
    jdbc: ""

# by default the following languages are supported: en_us, de_de
  language: "en_us"
# If categories are enabled the left row of the Auctionhouse UI will display the configured Categories as Items. If disabled the bottom row will include the categories button item and
  categories: true



# if the economy provider is set to "file" it will use these settings:
economy:
  default_balance: 1000

