messages:
  listings:
    title: "<r><gray>Marktplatz"
    item:
      display_name: "<r><gray>(<b><green>{PRICE}</green></b><yellow>$</yellow>)</gray><white>"
      lore_header:
        - "<r><gray>LinksKlick zum Kaufen"
        - "<r><gray>RechtsKlick für Mehr Informationen"
  listing_info:
    title: "<r><gray>Marktplatz"
