messages:
  listings:
    title: "<reset><gray>Marktplatz"
    sort_item:
      material: "HOPPER"
      display_name: "<gray>Sortieren"
      options:
        enabled:
          name_a_z: ""
          name_z_a: ""
          price_h_l: ""
          price_l_h: ""
          price_per_piece_h_l: ""
          price_per_piece_l_h: ""
        disabled:
          name_a_z: ""
          name_z_a: ""
          price_h_l: ""
          price_l_h: ""
          price_per_piece_h_l: ""
          price_per_piece_l_h: ""
    item:
      display_name: "<gray>(<b><green>{PRICE}</green></b><yellow>$</yellow>)</gray><white>{ITEM_NAME}"
      lore_header:
        - "<gray>LinksKlick zum Kaufen"
        - "<gray>RechtsKlick für Mehr Informationen"
  listing_info:
    # in listing_info the following placeholders are available: {SELLER_NAME}, {BUYER_BALANCE}, {ITEM_PRICE}, {ITEM_NAME}, {ITEM_DISPLAY_NAME}, {ITEM_COUNT}, {PRICE_PER_PIECE}
    title: "<gray>Marktplatz - Informationen"
    info_item:
      title: "<gray>Informationen zum Angebot von <light_gray>{SELLER_NAME}"
      lore:
        - "<gray>Preis<dark_gray>:<light_gray> {ITEM_PRICE}$ <dark_gray>(<gray>{PRICE_PER_PIECE}$ pro Stück</gray>)"
        - "<gray>Item<dark_gray>:<light_gray> {ITEM_NAME}"
        - "gray>Stückzahl<dark_gray>:<light_gray> {ITEM_COUNT}"



categories:
  filter0:
    item:
      material: BARRIER
      amount: 1
      display-name: "<gray>Filter Deaktivieren</gray>"
      lore:
        - "<gray>klicken um Filter zu deaktivieren"
      unbreakable: true
      hide-flags: true
    rules:
      - "**"
  filter1:
      item:
        material: SANDSTONE
        amount: 1
        display-name: "<gray>Baumaterialien</gray>"
        lore:
          - "<gray>klicken um Filter zu aktivieren"
        unbreakable: true
        hide-flags: true
      rules:
        - "*STONE*"
        - "*PICKAXE*"
        - "*SHOVEL*"
        - "*AXE*"
  filter2:
    item:
      material: STONE
      amount: 1
      display-name: "<gold>Filter2</gold>"
      lore:
        - "<gray>Erste Zeile"
        - "<gray>Zweite Zeile"
      unbreakable: true
      hide-flags: true
    rules:
      - "*GOLD*"
      - "*IRON*"
      - "*DEEPSLATE*"
      - "*AXE*"
  filter3:
    item:
      material: BARRIER
      amount: 1
      display-name: "<gray>Filter Deaktivieren</gray>"
      lore:
        - "<gray>klicken um Filter zu deaktivieren"
      unbreakable: true
      hide-flags: true
    rules:
      - "*"
  filter4:
    item:
      material: SANDSTONE
      amount: 1
      display-name: "<gray>Baumaterialien</gray>"
      lore:
        - "<gray>klicken um Filter zu aktivieren"
      unbreakable: true
      hide-flags: true
    rules:
      - "*STONE*"
      - "*PICKAXE*"
      - "*SHOVEL*"
      - "*AXE*"
  filter5:
    item:
      material: STONE
      amount: 1
      display-name: "<gold>Filter2</gold>"
      lore:
        - "<gray>Erste Zeile"
        - "<gray>Zweite Zeile"
      unbreakable: true
      hide-flags: true
    rules:
      - "*GOLD*"
      - "*IRON*"
      - "*DEEPSLATE*"
      - "*AXE*"

settings:
  economy:
    tax_percentage: 10
#    supported economy providers at the time are:
#      plugins: "astraeconomy", "vault", "coinsengine" ...
#      other: "auto", "file".
#    setting this to auto will use the first compatible plugin in the order they are written above.
#    if none work it will use a file to store balances and provide basic commands for players to use money.
#    keep in mind that the built in economy is not compatible with other plugins and is intended for small servers where the Auctionhouse is the only way players interact with money
    provider: "auto"

# by default the following languages are supported: en_us, de_de
  language: "en_us"

# if the economy provider is set to "file" it will use these settings:
economy:
  default_balance: 1000

items:
  buttons:
    insert:
    my_listings:
    prev_page:
      material: ARROW
      amount: 1
      display-name: "<gray>Vorherige Seite"
      lore:
       - "<gray>Klicke um zur vorherigen Seite"
       - "<gray>Der angebote zu kommen"
      unbreakable: true
      hide-flags: true
    next_page:
      material: ARROW
      amount: 1
      display-name: "<gray>Nächste Seite"
      lore:
        - "<gray>Klicke um zur Nächsten Seite"
        - "<gray>Der angebote zu kommen"
      unbreakable: true
      hide-flags: true
    prev_category:
      material: SPECTRAL_ARROW
      amount: 1
      display-name: "<gray>Kategorien Hochscrollen"
      lore:
        - "<gray>Klicke um Die Verfügbaren"
        - "<gray>Kategorien Hoch zu scrollen"
      unbreakable: true
      hide-flags: true
    next_category:
      material: SPECTRAL_ARROW
      amount: 1
      display-name: "<gray>Kategorien Runterscrollen"
      lore:
        - "<gray>Klicke um Die Verfügbaren"
        - "<gray>Kategorien Runter zu scrollen"
      unbreakable: true
      hide-flags: true
    home:
    scroll_categories_down:
    scroll_categories_up: