name: AstraAH
version: '1.0'
main: dev.veyno.astraAH.AstraAH
api-version: '1.21'
authors: [ veyno ]
website: https://veyno.dev
folia-supported: true

depend:
  - packetevents

softdepend:
  - Vault

commands:
  market:

permissions:
  astraah:
    actions:
      sub_setting:
        showadvancedcategories:
          default: true
        showadvancedhistory:
          default: true
        reloadonopen:
          default: true
        defaultfilter:
          default: true
        defaultsort:
          default: true
      categories:
        default: true
      settings:
        default: true
      my_listings:
        default: true
      refresh:
        default: true
      sort:
        default: true
      search:
        default: true
      history:
        default: true
